[2022-10-11 15:22:31,423][set_app.py 557][INFO]: 退出登录成功，用例无异常！
